filenames_file_eval: data_splits/ktti_test.csv
data_path_eval: /hdd/Automotive_Perception_Group/team_2/kitti_dataset
dataset: kitti
max_depth: 80
min_depth: 0.001
do_kb_crop: True
garg_crop: True
input_dir: /hdd/hoa_2/models/depth/custom_decoders
normalize: False
to_grayscale: False
