project_name: Hyundai_Mobis_OMS
model_application: DepthEstimation_dev
model_architecture: Unet
model_version: 1.0

input_height: 480
input_width: 640

source_code: https://github.com/DeltaX-AI-Lab/mobis-oms-depth-estimation
pre_processing: ade20k
post_processing: ade20k

checkpoint_path: /hdd/hoa/models/oms/nyu_regnetx016gf_metricleres_qat/model-15855-best_silog_14.59763.ckpt
output_path: /hdd/hoa/checkpoints/nyu_regnetx016gf_metricleres_qat.onnx