comment: kitti_metric_depth

mode: train
framework: 2
model_name: kitti_tiyolov8s_metricleres
encoder: tiyolov8s
decoder: metricleres
pretrained: True
normalize: False

replace_silu: True
use_customsilu: True

batch_size: 8
learning_rate_ratio: 1.0

dataset: kitti
filenames_file: data_splits/kitti_train.csv
data_path: path/to/kitti

num_epochs: 50
learning_rate: 0.00005
weight_decay: 1e-2
adam_eps: 1e-3
num_threads: 1
input_height: 352
input_width: 1120 
max_depth: 80
min_depth: 0.001
do_random_rotate: True
degree: 1.0

log_dir: path/to/log_dir/
gpu: 0
init_type: normal
loss_func: zoe
log_freq: 100
do_online_eval: True
# eval_freq: 500
filenames_file_eval: data_splits/kitti_test.csv
do_kb_crop: True
garg_crop: True

use_early_stopping: True
lr_patience: 5